env_name: reacher-cs285-v0
exp_name: P4-es2

base_config: mpc
num_layers: 2
hidden_size: 250

num_iters: 15
initial_batch_size: 5000
batch_size: 800
num_agent_train_steps_per_iter: 1000
num_eval_trajectories: 10
mpc_strategy: random

# change these!
mpc_num_action_sequences: 1000
mpc_horizon: 10
ensemble_size: 2


