env_name: cheetah-cs285-v0
exp_name: cheetah_mbpo

base_config: mpc
num_layers: 2
hidden_size: 250

num_iters: 10
initial_batch_size: 5000
batch_size: 5000
num_agent_train_steps_per_iter: 1500
num_eval_trajectories: 10

